/*******************************************************************************
* This file was generated by Tizen Web UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/

/**
 * @type {uibinding.dataSource}
 * @param {Object} options - dataSource options
 */
var dataSource = function () {};

/**
 * @type {Object}
 */
dataSource.prototype.data = {};

/**
 * @type {Object}
 */
dataSource.prototype.handlers = {
		"success" : [],
		"error" : [],
		"complete": []
};

/**
 * @param 
 */
dataSource.prototype.update = function (options) { };

/**
 * @returns {Object}
 */
dataSource.prototype.getData = function () { };

/**
 * @param {String} name
 * @param {Function} callback
 */
dataSource.prototype.addHandler = function (name, callback) {};

/**
 * @base {uibinding.dataSource}
 * @type {uibinding.dataSourceRemote}
 * @param {Object} options - dataSourceRemote options
 */
function dataSourceRemote () {}
dataSourceRemote.prototype = new dataSource();
/**
 * @base {uibinding.dataSource}
 * @type {uibinding.dataStatic}
 * @param {Object} options - dataSourceStatic options
 */
function dataSourceStatic () {}
dataSourceStatic.prototype = new dataSource();
/**
 * @base {uibinding.dataSource}
 * @type {uibinding.dataSourceContact}
 * @param {Object} options - dataSourceContact options
 */
function dataSourceContact () {}
dataSourceContact.prototype = new dataSource();
/**
 * @base {uibinding.dataSource}
 * @type {uibinding.dataSourceCalendar}
 * @param {Object} options - dataSourceCalendar options
 */
function dataSourceCalendar () {}
dataSourceCalendar.prototype = new dataSource();
/**
 * @base {uibinding.dataSource}
 * @type {uibinding.dataSourceCallhistory}
 * @param {Object} options - dataSourceCallhistory options
 */
function dataSourceCallhistory () {}
dataSourceCallhistory.prototype = new dataSource();
/**
 * @base {uibinding.dataSource}
 * @type {uibinding.dataSourceFile}
 * @param {Object} options - dataSourceFile options
 */
function dataSourceFile () {}
dataSourceFile.prototype = new dataSource();

/** 
 * @namespace uibinding
 */
function uibinding () { };
uibinding.prototype.dataSource = function dataSource (options) { };
uibinding.prototype.dataSourceRemote = function dataSourceRemote (options) { };
uibinding.prototype.dataSourceStatic = function dataSourceStatic (options) { };
uibinding.prototype.dataSourceContact = function dataSourceContact (options) { };
uibinding.prototype.dataSourceCalendar = function dataSourceCalendar (options) { };
uibinding.prototype.dataSourceCallhistory = function dataSourceCallhistory (options) { };
uibinding.prototype.dataSourceFile = function dataSourceFile (options) { };

var uibinding = new uibinding();





function ds () { };

_app.prototype.ds = new ds();

function dm () { };

_app.prototype.dm = new dm();
