/*******************************************************************************
* This file was generated by Tizen Web UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/
/**
 * @method init
 * @param {Object} event
 * @inheritdoc _app.init
 * @extends _app.init
 * @alias init
 * @member app
 */
app.init = function() {

    var newpage1 = new _page1_page();
    newpage1.init_page();

    var newFavorites = new _Favorites_page();
    newFavorites.init_page();

    var newpage2 = new _page2_page();
    newpage2.init_page();

    var newNewFavorite = new _NewFavorite_page();
    newNewFavorite.init_page();

    var newMap = new _Map_page();
    newMap.init_page();

    var newMapBis = new _MapBis_page();
    newMapBis.init_page();

    var newpage3 = new _page3_page();
    newpage3.init_page();

    var newpage4 = new _page4_page();
    newpage4.init_page();

};

// page classes
    
/**
*    Object _page1_page()
*    @super _page
*    @constructor
*    @memberOf_page1_page
*/
function _page1_page() {
}

// inherit _page
_page1_page.prototype = new _page("page1");

// widget assist
_page1_page.prototype.header1 = undefined;
_page1_page.prototype.headingone1 = undefined;
_page1_page.prototype.content1 = undefined;
_page1_page.prototype.newAlarm = undefined;
_page1_page.prototype.existingAlarm = undefined;
_page1_page.prototype.newFavorite = undefined;
_page1_page.prototype.existingFavorite = undefined;

// default widget event handler

_page1_page.prototype.init_page = function() {
    this._init_page(function() {

		// page object
        _page1_page.prototype.obj = document.getElementById(_page1_page.prototype.pageID);
        _page1_page.prototype.tauObj = tau.widget.Page(_page1_page.prototype.obj);

		// widget assist (real object binding)

		/**
		 * @type {Element}
		 */
        _page1_page.prototype.header1 = document.getElementById("header1");

		/**
		 * @type {Element}
		 */
        _page1_page.prototype.headingone1 = document.getElementById("headingone1");

		/**
		 * @type {Element}
		 */
        _page1_page.prototype.content1 = document.getElementById("content1");

		/**
		 * @type {Element}
		 */
        _page1_page.prototype.newAlarm = document.getElementById("newAlarm");

		/**
		 * @type {Element}
		 */
        _page1_page.prototype.existingAlarm = document.getElementById("existingAlarm");

		/**
		 * @type {Element}
		 */
        _page1_page.prototype.newFavorite = document.getElementById("newFavorite");

		/**
		 * @type {Element}
		 */
        _page1_page.prototype.existingFavorite = document.getElementById("existingFavorite");


		// bind widget event handler
        tau.event.on(document.querySelectorAll("#newAlarm"), "tap", function(event) { _page1_page.prototype.changePage(document.getElementById("page2"), {transition :"fade", reverse : true}); });
        tau.event.on(document.querySelectorAll("#existingAlarm"), "tap", function(event) { _page1_page.prototype.changePage(document.getElementById("page4"), {transition :"fade", reverse : true}); });
        tau.event.on(document.querySelectorAll("#newFavorite"), "tap", function(event) { _page1_page.prototype.changePage(document.getElementById("NewFavorite"), {transition :"fade", reverse : true}); });
        tau.event.on(document.querySelectorAll("#existingFavorite"), "tap", function(event) { _page1_page.prototype.changePage(document.getElementById("page3"), {transition :"fade", reverse : true}); });

    });


};
/**
*    Object _Favorites_page()
*    @super _page
*    @constructor
*    @memberOf_Favorites_page
*/
function _Favorites_page() {
}

// inherit _page
_Favorites_page.prototype = new _page("Favorites");

// widget assist
_Favorites_page.prototype.header5 = undefined;
_Favorites_page.prototype.headingone5 = undefined;
_Favorites_page.prototype.content5 = undefined;
_Favorites_page.prototype.alarmsFavorite = undefined;
_Favorites_page.prototype.button7 = undefined;

// default widget event handler

_Favorites_page.prototype.init_page = function() {
    this._init_page(function() {

		// page object
        _Favorites_page.prototype.obj = document.getElementById(_Favorites_page.prototype.pageID);
        _Favorites_page.prototype.tauObj = tau.widget.Page(_Favorites_page.prototype.obj);

		// widget assist (real object binding)

		/**
		 * @type {Element}
		 */
        _Favorites_page.prototype.header5 = document.getElementById("header5");

		/**
		 * @type {Element}
		 */
        _Favorites_page.prototype.headingone5 = document.getElementById("headingone5");

		/**
		 * @type {Element}
		 */
        _Favorites_page.prototype.content5 = document.getElementById("content5");

		/**
		 * @type {Element}
		 */
        _Favorites_page.prototype.alarmsFavorite = document.getElementById("alarmsFavorite");

		/**
		 * @type {Element}
		 */
        _Favorites_page.prototype.button7 = document.getElementById("button7");


		// bind widget event handler
        tau.event.on(document.querySelectorAll("#button7"), "tap", function(event) { _Favorites_page.prototype.changePage(document.getElementById("page2"), {transition :"fade", reverse : true}); });

    });


};
/**
*    Object _page2_page()
*    @super _page
*    @constructor
*    @memberOf_page2_page
*/
function _page2_page() {
}

// inherit _page
_page2_page.prototype = new _page("page2");

// widget assist
_page2_page.prototype.header2 = undefined;
_page2_page.prototype.headingone2 = undefined;
_page2_page.prototype.content2 = undefined;
_page2_page.prototype.label1 = undefined;
_page2_page.prototype.alarmName = undefined;
_page2_page.prototype.label2 = undefined;
_page2_page.prototype.alarmLat = undefined;
_page2_page.prototype.alarmLong = undefined;
_page2_page.prototype.map = undefined;
_page2_page.prototype.favorite = undefined;
_page2_page.prototype.label3 = undefined;
_page2_page.prototype.alarmComment = undefined;
_page2_page.prototype.label4 = undefined;
_page2_page.prototype.alarmDistance = undefined;
_page2_page.prototype.button2 = undefined;

// default widget event handler
_page2_page.prototype.button2_ontap = function(event) {};

_page2_page.prototype.init_page = function() {
    this._init_page(function() {

		// page object
        _page2_page.prototype.obj = document.getElementById(_page2_page.prototype.pageID);
        _page2_page.prototype.tauObj = tau.widget.Page(_page2_page.prototype.obj);

		// widget assist (real object binding)

		/**
		 * @type {Element}
		 */
        _page2_page.prototype.header2 = document.getElementById("header2");

		/**
		 * @type {Element}
		 */
        _page2_page.prototype.headingone2 = document.getElementById("headingone2");

		/**
		 * @type {Element}
		 */
        _page2_page.prototype.content2 = document.getElementById("content2");

		/**
		 * @type {Element}
		 */
        _page2_page.prototype.label1 = document.getElementById("label1");

		/**
		 * @type {Element}
		 */
        _page2_page.prototype.alarmName = document.getElementById("alarmName");

		/**
		 * @type {Element}
		 */
        _page2_page.prototype.label2 = document.getElementById("label2");

		/**
		 * @type {Element}
		 */
        _page2_page.prototype.alarmLat = document.getElementById("alarmLat");

		/**
		 * @type {Element}
		 */
        _page2_page.prototype.alarmLong = document.getElementById("alarmLong");

		/**
		 * @type {Element}
		 */
        _page2_page.prototype.map = document.getElementById("map");

		/**
		 * @type {Element}
		 */
        _page2_page.prototype.favorite = document.getElementById("favorite");

		/**
		 * @type {Element}
		 */
        _page2_page.prototype.label3 = document.getElementById("label3");

		/**
		 * @type {Element}
		 */
        _page2_page.prototype.alarmComment = document.getElementById("alarmComment");

		/**
		 * @type {Element}
		 */
        _page2_page.prototype.label4 = document.getElementById("label4");

		/**
		 * @type {Element}
		 */
        _page2_page.prototype.alarmDistance = document.getElementById("alarmDistance");

		/**
		 * @type {Element}
		 */
        _page2_page.prototype.button2 = document.getElementById("button2");


		// bind widget event handler
        tau.event.on(document.querySelectorAll("#map"), "tap", function(event) { _page2_page.prototype.changePage(document.getElementById("MapBis"), {transition :"fade", reverse : true}); });
        tau.event.on(document.querySelectorAll("#favorite"), "tap", function(event) { _page2_page.prototype.changePage(document.getElementById("Favorites"), {transition :"fade", reverse : true}); });
        tau.event.on(document.querySelectorAll("#button2"), "tap", function(event) { _page2_page.prototype.changePage(document.getElementById("page1"), {transition :"fade", reverse : true}); });
        tau.event.on(document.querySelectorAll("#button2"), "tap", function(event) { _page2_page.prototype.button2_ontap(event); });

    });


};
/**
*    Object _NewFavorite_page()
*    @super _page
*    @constructor
*    @memberOf_NewFavorite_page
*/
function _NewFavorite_page() {
}

// inherit _page
_NewFavorite_page.prototype = new _page("NewFavorite");

// widget assist
_NewFavorite_page.prototype.header3 = undefined;
_NewFavorite_page.prototype.headingone3 = undefined;
_NewFavorite_page.prototype.content3 = undefined;
_NewFavorite_page.prototype.label5 = undefined;
_NewFavorite_page.prototype.favoriteName = undefined;
_NewFavorite_page.prototype.label6 = undefined;
_NewFavorite_page.prototype.favoriteLat = undefined;
_NewFavorite_page.prototype.favoriteLong = undefined;
_NewFavorite_page.prototype.map2 = undefined;
_NewFavorite_page.prototype.button3 = undefined;

// default widget event handler
_NewFavorite_page.prototype.button3_ontap = function(event) {};

_NewFavorite_page.prototype.init_page = function() {
    this._init_page(function() {

		// page object
        _NewFavorite_page.prototype.obj = document.getElementById(_NewFavorite_page.prototype.pageID);
        _NewFavorite_page.prototype.tauObj = tau.widget.Page(_NewFavorite_page.prototype.obj);

		// widget assist (real object binding)

		/**
		 * @type {Element}
		 */
        _NewFavorite_page.prototype.header3 = document.getElementById("header3");

		/**
		 * @type {Element}
		 */
        _NewFavorite_page.prototype.headingone3 = document.getElementById("headingone3");

		/**
		 * @type {Element}
		 */
        _NewFavorite_page.prototype.content3 = document.getElementById("content3");

		/**
		 * @type {Element}
		 */
        _NewFavorite_page.prototype.label5 = document.getElementById("label5");

		/**
		 * @type {Element}
		 */
        _NewFavorite_page.prototype.favoriteName = document.getElementById("favoriteName");

		/**
		 * @type {Element}
		 */
        _NewFavorite_page.prototype.label6 = document.getElementById("label6");

		/**
		 * @type {Element}
		 */
        _NewFavorite_page.prototype.favoriteLat = document.getElementById("favoriteLat");

		/**
		 * @type {Element}
		 */
        _NewFavorite_page.prototype.favoriteLong = document.getElementById("favoriteLong");

		/**
		 * @type {Element}
		 */
        _NewFavorite_page.prototype.map2 = document.getElementById("map2");

		/**
		 * @type {Element}
		 */
        _NewFavorite_page.prototype.button3 = document.getElementById("button3");


		// bind widget event handler
        tau.event.on(document.querySelectorAll("#map2"), "tap", function(event) { _NewFavorite_page.prototype.changePage(document.getElementById("MapBis"), {transition :"fade", reverse : true}); });
        tau.event.on(document.querySelectorAll("#button3"), "tap", function(event) { _NewFavorite_page.prototype.changePage(document.getElementById("page1"), {transition :"fade", reverse : true}); });
        tau.event.on(document.querySelectorAll("#button3"), "tap", function(event) { _NewFavorite_page.prototype.button3_ontap(event); });

    });


};
/**
*    Object _Map_page()
*    @super _page
*    @constructor
*    @memberOf_Map_page
*/
function _Map_page() {
}

// inherit _page
_Map_page.prototype = new _page("Map");

// widget assist
_Map_page.prototype.header6 = undefined;
_Map_page.prototype.headingone6 = undefined;
_Map_page.prototype.button1 = undefined;

// default widget event handler

_Map_page.prototype.init_page = function() {
    this._init_page(function() {

		// page object
        _Map_page.prototype.obj = document.getElementById(_Map_page.prototype.pageID);
        _Map_page.prototype.tauObj = tau.widget.Page(_Map_page.prototype.obj);

		// widget assist (real object binding)

		/**
		 * @type {Element}
		 */
        _Map_page.prototype.header6 = document.getElementById("header6");

		/**
		 * @type {Element}
		 */
        _Map_page.prototype.headingone6 = document.getElementById("headingone6");

		/**
		 * @type {Element}
		 */
        _Map_page.prototype.button1 = document.getElementById("button1");


		// bind widget event handler
        tau.event.on(document.querySelectorAll("#button1"), "tap", function(event) { _Map_page.prototype.changePage(document.getElementById("Previouse Page"), {transition :"fade", reverse : true}); });

    });


};
/**
*    Object _MapBis_page()
*    @super _page
*    @constructor
*    @memberOf_MapBis_page
*/
function _MapBis_page() {
}

// inherit _page
_MapBis_page.prototype = new _page("MapBis");

// widget assist
_MapBis_page.prototype.header4 = undefined;
_MapBis_page.prototype.headingone4 = undefined;
_MapBis_page.prototype.content4 = undefined;
_MapBis_page.prototype.button6 = undefined;

// default widget event handler

_MapBis_page.prototype.init_page = function() {
    this._init_page(function() {

		// page object
        _MapBis_page.prototype.obj = document.getElementById(_MapBis_page.prototype.pageID);
        _MapBis_page.prototype.tauObj = tau.widget.Page(_MapBis_page.prototype.obj);

		// widget assist (real object binding)

		/**
		 * @type {Element}
		 */
        _MapBis_page.prototype.header4 = document.getElementById("header4");

		/**
		 * @type {Element}
		 */
        _MapBis_page.prototype.headingone4 = document.getElementById("headingone4");

		/**
		 * @type {Element}
		 */
        _MapBis_page.prototype.content4 = document.getElementById("content4");

		/**
		 * @type {Element}
		 */
        _MapBis_page.prototype.button6 = document.getElementById("button6");


		// bind widget event handler
        tau.event.on(document.querySelectorAll("#button6"), "tap", function(event) { _MapBis_page.prototype.changePage(document.getElementById("Previouse Page"), {transition :"fade", reverse : false}); });

    });


};
/**
*    Object _page3_page()
*    @super _page
*    @constructor
*    @memberOf_page3_page
*/
function _page3_page() {
}

// inherit _page
_page3_page.prototype = new _page("page3");

// widget assist
_page3_page.prototype.header7 = undefined;
_page3_page.prototype.headingone7 = undefined;
_page3_page.prototype.content6 = undefined;
_page3_page.prototype.favorites = undefined;
_page3_page.prototype.button4 = undefined;

// default widget event handler

_page3_page.prototype.init_page = function() {
    this._init_page(function() {

		// page object
        _page3_page.prototype.obj = document.getElementById(_page3_page.prototype.pageID);
        _page3_page.prototype.tauObj = tau.widget.Page(_page3_page.prototype.obj);

		// widget assist (real object binding)

		/**
		 * @type {Element}
		 */
        _page3_page.prototype.header7 = document.getElementById("header7");

		/**
		 * @type {Element}
		 */
        _page3_page.prototype.headingone7 = document.getElementById("headingone7");

		/**
		 * @type {Element}
		 */
        _page3_page.prototype.content6 = document.getElementById("content6");

		/**
		 * @type {Element}
		 */
        _page3_page.prototype.favorites = document.getElementById("favorites");

		/**
		 * @type {Element}
		 */
        _page3_page.prototype.button4 = document.getElementById("button4");


		// bind widget event handler
        tau.event.on(document.querySelectorAll("#button4"), "tap", function(event) { _page3_page.prototype.changePage(document.getElementById("page1"), {transition :"fade", reverse : false}); });

    });


};
/**
*    Object _page4_page()
*    @super _page
*    @constructor
*    @memberOf_page4_page
*/
function _page4_page() {
}

// inherit _page
_page4_page.prototype = new _page("page4");

// widget assist
_page4_page.prototype.header8 = undefined;
_page4_page.prototype.headingone8 = undefined;
_page4_page.prototype.content7 = undefined;
_page4_page.prototype.alarms = undefined;
_page4_page.prototype.button5 = undefined;

// default widget event handler

_page4_page.prototype.init_page = function() {
    this._init_page(function() {

		// page object
        _page4_page.prototype.obj = document.getElementById(_page4_page.prototype.pageID);
        _page4_page.prototype.tauObj = tau.widget.Page(_page4_page.prototype.obj);

		// widget assist (real object binding)

		/**
		 * @type {Element}
		 */
        _page4_page.prototype.header8 = document.getElementById("header8");

		/**
		 * @type {Element}
		 */
        _page4_page.prototype.headingone8 = document.getElementById("headingone8");

		/**
		 * @type {Element}
		 */
        _page4_page.prototype.content7 = document.getElementById("content7");

		/**
		 * @type {Element}
		 */
        _page4_page.prototype.alarms = document.getElementById("alarms");

		/**
		 * @type {Element}
		 */
        _page4_page.prototype.button5 = document.getElementById("button5");


		// bind widget event handler
        tau.event.on(document.querySelectorAll("#button5"), "tap", function(event) { _page4_page.prototype.changePage(document.getElementById("page1"), {transition :"fade", reverse : false}); });

    });


};
