<?xml version="1.0" encoding="utf-8" ?>
<xsl:stylesheet version="1.0"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="text" encoding="utf-8" indent="yes" />

	<xsl:variable name="tab">
		<xsl:text>    </xsl:text>
	</xsl:variable>
	<xsl:variable name="newline">
		<xsl:text>
</xsl:text>
	</xsl:variable>

	<xsl:template match="/">
		<xsl:text><![CDATA[/*******************************************************************************
* This file was generated by Tizen Web UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/
]]></xsl:text>

		<xsl:apply-templates select="/tizen.nscreen" />
	</xsl:template>
	
	<xsl:template name="screenDescLayer">
	    <xsl:param name="screenDescName" />
	    
	    <xsl:for-each select="/tizen.nscreen/screenDescLayers/screenDescLayer[@name = $screenDescName]/screenDesc/property">
 			
 			<xsl:text> and ( </xsl:text>

			<xsl:if test="@name = 'deviceWidth'">
 				<xsl:text>device-width</xsl:text>
 			</xsl:if> 
 			<xsl:if test="@name = 'deviceHeight'">
 				<xsl:text>device-height</xsl:text>
 			</xsl:if> 
 			<xsl:if test="@name = 'devicePixelRatio'">
 				<xsl:text>-webkit-device-pixel-ratio</xsl:text>
 			</xsl:if> 
 			<xsl:if test="@name != 'devicePixelRatio' and @name != 'deviceHeight' and @name != 'deviceWidth'">
 				<xsl:value-of select="@name"/>
 			</xsl:if>
 			
 			<xsl:text> : </xsl:text><xsl:value-of select="@value"/>

 			<xsl:if test="@name = 'deviceWidth' or @name = 'deviceHeight'">
 				<xsl:text>px</xsl:text>
 			</xsl:if> 

 			<xsl:text> )</xsl:text>

 		</xsl:for-each>
 		
 		<xsl:text>;</xsl:text>
 		<xsl:value-of select="$newline"/>
	</xsl:template>
	
	<xsl:template name="screenProvider">
		
	</xsl:template>
	
	<xsl:template name="styleSheetLayer">
		<xsl:param name="pageId" />
	    <xsl:param name="screenDescName" />
		
		
		<xsl:text>@import url("</xsl:text>
		
		
		<xsl:value-of select="/tizen.nscreen/styleSheetLayers/styleSheetLayer[@pageId = $pageId and @screenDescName= $screenDescName]/@filePath"/>
		<xsl:text>") screen </xsl:text>	
			
		<xsl:call-template name="screenDescLayer">
				<xsl:with-param name="screenDescName" select="@screenDescName" />
			</xsl:call-template>
	</xsl:template>

	<xsl:template match="tizen.nscreen">
				
		<xsl:for-each select="screenProviders/screenProvider">
			
			<xsl:variable name="pageName"><xsl:value-of select="@pageId"/></xsl:variable>
			<xsl:variable name="screenDescName"><xsl:value-of select="@screenDescName"/></xsl:variable>

			<xsl:call-template name="styleSheetLayer">
				<xsl:with-param name="pageId" select="@pageId" />
				<xsl:with-param name="screenDescName" select="@screenDescName" />
			</xsl:call-template>

			<xsl:for-each select="./screenProvider">
				<xsl:call-template name="styleSheetLayer">
					<xsl:with-param name="pageId" select="$pageName" />
					<xsl:with-param name="screenDescName" select="$screenDescName" />
				</xsl:call-template>
			</xsl:for-each>
		</xsl:for-each>
	</xsl:template>
</xsl:stylesheet>

