<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="text"/>

<xsl:variable name="tab"><xsl:text>    </xsl:text></xsl:variable>
<xsl:variable name="newline"><xsl:text>
</xsl:text></xsl:variable>
<xsl:variable name="startup_page" select="//page[@startup='true']"/>

<xsl:template match="/">
<xsl:text>/*******************************************************************************
* This file was generated by Tizen Web UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/

/**
 * @type {uibinding.dataSource}
 * @param {Object} options - dataSource options
 */
var dataSource = function () {};

/**
 * @type {Object}
 */
dataSource.prototype.data = {};

/**
 * @type {Object}
 */
dataSource.prototype.handlers = {
		"success" : [],
		"error" : [],
		"complete": []
};

/**
 * @param 
 */
dataSource.prototype.update = function (options) { };

/**
 * @returns {Object}
 */
dataSource.prototype.getData = function () { };

/**
 * @param {String} name
 * @param {Function} callback
 */
dataSource.prototype.addHandler = function (name, callback) {};

/**
 * @base {uibinding.dataSource}
 * @type {uibinding.dataSourceRemote}
 * @param {Object} options - dataSourceRemote options
 */
function dataSourceRemote () {}
dataSourceRemote.prototype = new dataSource();
/**
 * @base {uibinding.dataSource}
 * @type {uibinding.dataStatic}
 * @param {Object} options - dataSourceStatic options
 */
function dataSourceStatic () {}
dataSourceStatic.prototype = new dataSource();
/**
 * @base {uibinding.dataSource}
 * @type {uibinding.dataSourceContact}
 * @param {Object} options - dataSourceContact options
 */
function dataSourceContact () {}
dataSourceContact.prototype = new dataSource();
/**
 * @base {uibinding.dataSource}
 * @type {uibinding.dataSourceCalendar}
 * @param {Object} options - dataSourceCalendar options
 */
function dataSourceCalendar () {}
dataSourceCalendar.prototype = new dataSource();
/**
 * @base {uibinding.dataSource}
 * @type {uibinding.dataSourceCallhistory}
 * @param {Object} options - dataSourceCallhistory options
 */
function dataSourceCallhistory () {}
dataSourceCallhistory.prototype = new dataSource();
/**
 * @base {uibinding.dataSource}
 * @type {uibinding.dataSourceFile}
 * @param {Object} options - dataSourceFile options
 */
function dataSourceFile () {}
dataSourceFile.prototype = new dataSource();

/** 
 * @namespace uibinding
 */
function uibinding () { };
uibinding.prototype.dataSource = function dataSource (options) { };
uibinding.prototype.dataSourceRemote = function dataSourceRemote (options) { };
uibinding.prototype.dataSourceStatic = function dataSourceStatic (options) { };
uibinding.prototype.dataSourceContact = function dataSourceContact (options) { };
uibinding.prototype.dataSourceCalendar = function dataSourceCalendar (options) { };
uibinding.prototype.dataSourceCallhistory = function dataSourceCallhistory (options) { };
uibinding.prototype.dataSourceFile = function dataSourceFile (options) { };

var uibinding = new uibinding();




</xsl:text>

<xsl:text>
function ds () { };
</xsl:text>
<xsl:apply-templates select="//dataSource" />
<xsl:text>
_app.prototype.ds = new ds();
</xsl:text>

<xsl:text>
function dm () { };
</xsl:text>
<xsl:apply-templates select="//viewModel"/>
<xsl:text>
_app.prototype.dm = new dm();
</xsl:text>
</xsl:template>


<xsl:template match="dataSource">
<xsl:variable name="dataModel_name" select="@dataSource" />
<xsl:variable name="newDataSource" select="concat('ds.prototype.', $dataModel_name, ' = new uibinding.')" />

<xsl:choose>
	<xsl:when test="@modelType = 'Static'">
		<xsl:value-of
			select="concat($newDataSource, 'dataSourceStatic();', $newline)" />
	</xsl:when>
	<xsl:when test="@modelType = 'Remote Call'">
		<xsl:value-of
			select="concat($newDataSource, 'dataSourceRemote();', $newline)" />
	</xsl:when>
	<xsl:when test="@modelType = 'Contact'">
		<xsl:value-of
			select="concat($newDataSource, 'dataSourceContact();', $newline)" />
	</xsl:when>
	<xsl:when test="@modelType = 'Calendar'">
		<xsl:value-of
			select="concat($newDataSource, 'dataSourceCalendar();', $newline)" />
	</xsl:when>
	<xsl:when test="@modelType = 'Call History'">
		<xsl:value-of
			select="concat($newDataSource, 'dataSourceCallhistory();', $newline)" />
	</xsl:when>
	<xsl:when test="@modelType = 'File System'">
		<xsl:value-of
			select="concat($newDataSource, 'dataSourceFile();', $newline)" />
	</xsl:when>
</xsl:choose>
</xsl:template>

<xsl:template match="viewModel">
	<xsl:variable name="viewModelName" select="@name"/>
	<xsl:value-of select="concat('dm.prototype.', $viewModelName, ' = { };', $newline)"/>
</xsl:template>

</xsl:stylesheet>